title: João Henrique Vasconcelos # your name (or website title) here
logo: "/images/me_logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mechanical & Energy Engineering Masters Graduate at <a href="https://ense3.grenoble-inp.fr/en">Grenoble INP - Ense3</a>.
  <br><br>
  Intrested in how Data Engineering can help with Climate. Also into Optimization, AI, and just hard engineering problems like making things that fly ;) 
  <br><br>
  <a href="https://www.linkedin.com/in/jo%C3%A3o-henrique-vasconcelos-8a14a710a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
