title: João Henrique Vasconcelos # your name (or website title) here
logo: "/images/me_logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3rd Year Mechanical Engineering Student at <a href="http://www.ufrgs.br/english/home">UFRGS</a>, currently working on <a href="https://www.jusbrasil.com.br/home">Jusbrasil's</a> data platform.
  <br><br>
  Intrested in Data Science, Optimization, Machine Learning and Aerodynamics. 
  <br><br>
  <a href="https://www.linkedin.com/in/jo%C3%A3o-henrique-vasconcelos-8a14a710a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
